name: Deploy MonteSeuPC na VPS (Main)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Atualizar MonteSeuPC na VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /root/monte_seu_pc/MonteSeuPC 
            git checkout main
            git pull origin main
            docker-compose up -d --build
